import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="AI Sustainability Dashboard",
    layout="wide",
    page_icon="🌱"
)

# ---------------- DARK THEME ----------------
st.markdown(
    """
    <style>
    .stApp { background-color: #0e1117; color: white; }
    </style>
    """,
    unsafe_allow_html=True
)

# ---------------- TITLE ----------------
st.title("🌱 AI-Based Sustainability Dashboard")
st.caption(
    "Analyzing large-scale sustainability feedback data to detect "
    "resource usage trends across states and seasons."
)

# ---------------- CSV UPLOAD ----------------
uploaded_file = st.file_uploader(
    "📂 Upload Sustainability CSV",
    type=["csv"],
    help="Required columns: State, Resource, Month, Usage"
)

if uploaded_file:
    df = pd.read_csv(uploaded_file)
else:
    st.info("⬆️ Upload a CSV file to begin analysis.")
    st.stop()

required_cols = {"State", "Resource", "Month", "Usage"}
if not required_cols.issubset(df.columns):
    st.error("CSV must contain columns: State, Resource, Month, Usage")
    st.stop()

# ---------------- SIDEBAR FILTERS ----------------
st.sidebar.title("🔎 Filter Data")

selected_states = st.sidebar.multiselect(
    "Select State(s)",
    df["State"].unique(),
    default=df["State"].unique()
)

selected_resources = st.sidebar.multiselect(
    "Select Resource(s)",
    df["Resource"].unique(),
    default=df["Resource"].unique()
)

filtered_df = df[
    (df["State"].isin(selected_states)) &
    (df["Resource"].isin(selected_resources))
]

# Ensure correct month order
month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]
filtered_df["Month"] = pd.Categorical(
    filtered_df["Month"],
    categories=month_order,
    ordered=True
)
filtered_df = filtered_df.sort_values("Month")

# ---------------- MAIN TREND GRAPH ----------------
st.subheader("📈 Resource Usage Trends (Hover to Explore Details)")

fig = px.line(
    filtered_df,
    x="Month",
    y="Usage",
    color="Resource",
    line_group="State",
    markers=True,
    template="plotly_dark"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Usage Level (AI-derived index)",
    legend_title="Resource Type",
    hovermode="x unified",
    height=520
)

st.plotly_chart(fig, use_container_width=True)

# ---------------- SPIKE / ANOMALY ALERTS ----------------
st.markdown("---")
st.subheader("🚨 Anomaly & Spike Alerts")

alerts = []

for (state, resource), g in filtered_df.groupby(["State", "Resource"]):
    avg = g["Usage"].mean()
    spikes = g[g["Usage"] > avg * 1.25]
    if not spikes.empty:
        alerts.append(f"⚠️ Spike detected in **{state} – {resource}**")

if alerts:
    for a in alerts:
        st.error(a)
else:
    st.success("✅ No significant anomalies detected.")

# ---------------- INDIA HEATMAP ----------------
st.markdown("---")
st.subheader("🗺️ India State-wise Sustainability Heatmap")

heat_df = (
    df.groupby("State")["Usage"]
    .mean()
    .reset_index(name="Avg Usage")
)

fig_map = px.choropleth(
    heat_df,
    locations="State",
    locationmode="india states",
    color="Avg Usage",
    color_continuous_scale="Reds",
    title="Average Resource Usage Intensity by State",
    template="plotly_dark"
)

fig_map.update_geos(fitbounds="locations", visible=False)

st.plotly_chart(fig_map, use_container_width=True)

# ---------------- AI EXPLANATION PANEL ----------------
st.markdown("---")
st.subheader("🧠 AI Explanation")

top_state = heat_df.sort_values("Avg Usage", ascending=False).iloc[0]["State"]
top_resource = filtered_df["Resource"].value_counts().idxmax()

st.info(
    f"""
**Key Insights Generated by AI:**

• The state with the highest overall sustainability pressure is **{top_state}**.  
• The most impacted resource across selected filters is **{top_resource}**.  
• Detected spikes indicate potential seasonal or infrastructure-related stress.  

**Recommended Actions:**
- Prioritize audits in high-usage states
- Introduce demand optimization for stressed resources
- Monitor monthly trends for early warning signals
"""
)

# ---------------- DATA VIEW ----------------
with st.expander("📊 View Processed Data"):
    st.dataframe(filtered_df, use_container_width=True)
